datasets:
  deepfake:
    data_type: images
    build_info:
      annotations:
        train:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/train.json
          storage: /storage1/ruby/LAVIS/deepfake/annotations/for_testing.json
        val:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/val.json
          storage: /storage1/ruby/LAVIS/deepfake/annotations/for_testing.json     
        test:
          url: 
              - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
          storage: 
              - /storage1/ruby/LAVIS/deepfake/annotations/for_testing.json

      images:
        storage: ExDF/img

