datasets:
  deepfake:
    data_type: images
    build_info:
      annotations:
        train:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/train.json
          storage: ExDF/ann/train/train.json
        val:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/val.json
          storage: ExDF/ann/test/val.json 
        test:
          url:  https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
          storage: ExDF/ann/test/test.json

      images:
        storage: ExDF

