datasets:
  deepfake:
    data_type: images
    build_info:
      annotations:
        train:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/train.json
          storage: /home/u2272230/ExDF/ann/train/train-hive-ex.json
        val:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/val.json
          storage: /home/u2272230/ExDF/ann/test/val-hive-v2.json 
        test:
          url:  https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
          storage: /home/u2272230/ExDF/real.json

      images:
        storage: /home/u2272230/ExDF

