datasets:
  deepfake:
    data_type: images
    build_info:
      annotations:
        train:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/train.json
          storage: /storage1/ruby/LAVIS/deepfake/annotations/for_testing.json
        val:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/val.json
          storage: /storage1/ruby/LAVIS/deepfake/annotations/for_testing.json    
        test:
          url: 
              - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
              # - https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
          storage: 
              # - /storage1/ruby/thesis_dataset/ann/test/generation/random_text_input/ip2p-test.json

              - /storage1/ruby/LAVIS/deepfake/annotations/for_testing.json
              # - /storage1/ruby/thesis_dataset/ann/ff++/FaceShifter.json
              # - /storage1/ruby/thesis_dataset/ann/ff++/DeeperForensics.json
              # - /storage1/ruby/thesis_dataset/ann/ff++/CelebDF.json
              # - /storage1/ruby/thesis_dataset/ann/test/generation/random_text_input/hive-test.json
              # - /storage1/ruby/thesis_dataset/ann/test/generation/random_text_input/iDiff-test.json
              # - /storage1/ruby/thesis_dataset/ann/test/generation/random_text_input/mfg-test.json
      
      images:
        storage: /storage1/ruby/thesis_dataset

