datasets:
  deepfake:
    data_type: images
    build_info:
      annotations:
        train:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/train.json
          storage: /storage1/ruby/LAVIS/ExDF/ann/test/testing.json
        val:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/val.json
          storage: /storage1/ruby/LAVIS/ExDF/ann/test/testing.json  
        test:
          url: https://raw.githubusercontent.com/rorubyy/jsonfile/main/test.json
          storage: /storage1/ruby/LAVIS/ExDF/ann/test/testing.json

      images:
        storage: /storage1/ruby/LAVIS/ExDF

